### ISSUE TITLE
Does not starting compute nodes while running sbatch command

### ISSUE THREAD

**Issue by AMJAD195** [aws-samples/hpc-workshop-wrf#2]
Hi when I am running sbatch --ntasks 72  ${SCRIPTDIR}/slurm_run_wrf.sh  command the jobs are queued but the state of the node is still in idle and no compute node is creating in the aws ec2 console . i have followed all the same instructions mentioned in this video  https://www.youtube.com/watch?v=ZxrspLi28hw

**Comment by usumfabricae** [comment]
Hi AMJADMISTEO, 
sorry for the late reply, I just got back to wok this morning.
I'm running a full test on my environment since there're some minor updates I've done because of a new release of AWS Parallel Cluster (some small changes in the config file, but I think you already fixed them since they was not allowing to start-up the cluster properly) and on NCAR file format.

I think it will take a couple of hours to run the full test.

In the meanwhile could you please tell me if you are still experiencing this problem or if you already found a work-around?

BR

**Comment by usumfabricae** [comment]
Hi AMJADMISTEO,
I have recreated the whole environment from scratch following the script included in README.md and everything is working properly.

Are you still facing this issue?
Kind regards

**Comment by AMJAD195** [comment]
Hi thanks for the reply I have managed that issue everything is working
fine . Thanks

**Comment by AMJAD195** [comment]
Issue fixed
